# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 680)
        MainWindow.setMinimumSize(QtCore.QSize(900, 680))
        MainWindow.setMaximumSize(QtCore.QSize(900, 680))
        MainWindow.setWindowOpacity(63.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.input_buscar = QtGui.QLineEdit(self.centralwidget)
        self.input_buscar.setEnabled(True)
        self.input_buscar.setPlaceholderText("Escriba el título".decode('utf-8'))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_buscar.sizePolicy().hasHeightForWidth())
        self.input_buscar.setSizePolicy(sizePolicy)
        self.input_buscar.setMinimumSize(QtCore.QSize(0, 22))
        self.input_buscar.setInputMask(_fromUtf8(""))
        self.input_buscar.setObjectName(_fromUtf8("input_buscar"))
        self.horizontalLayout.addWidget(self.input_buscar)
        self.btn_buscar = QtGui.QPushButton(self.centralwidget)
        self.btn_buscar.setStyleSheet(_fromUtf8(""))
        self.btn_buscar.setText(_fromUtf8("Buscar"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Users/Lia/PycharmProjects/BookSearch/Design/ico_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setObjectName(_fromUtf8("btn_buscar"))
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.btn_busqueda_avanzada = QtGui.QPushButton(self.centralwidget)
        self.btn_busqueda_avanzada.setText(_fromUtf8("Búsqueda Avanzada"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Users/Lia/PycharmProjects/BookSearch/Design/ico_search_avance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_busqueda_avanzada.setIcon(icon1)
        self.btn_busqueda_avanzada.setObjectName(_fromUtf8("btn_busqueda_avanzada"))
        self.horizontalLayout.addWidget(self.btn_busqueda_avanzada)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_libros = QtGui.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_libros.setFont(font)
        self.list_libros.setLineWidth(1)
        self.list_libros.setObjectName(_fromUtf8("list_libros"))
        self.verticalLayout.addWidget(self.list_libros)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet(_fromUtf8("background :rgb(211, 211, 211)"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color:rgb(102, 102, 102)"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.pagina_value = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pagina_value.setFont(font)
        self.pagina_value.setStyleSheet(_fromUtf8("color:rgb(102, 102, 102)"))
        self.pagina_value.setObjectName(_fromUtf8("pagina_value"))
        self.horizontalLayout_2.addWidget(self.pagina_value)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_anterior = QtGui.QPushButton(self.widget_3)
        self.btn_anterior.setStyleSheet(_fromUtf8(""))
        self.btn_anterior.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Users/Lia/PycharmProjects/BookSearch/Design/ico_prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_anterior.setIcon(icon2)
        self.btn_anterior.setObjectName(_fromUtf8("btn_anterior"))
        self.horizontalLayout_2.addWidget(self.btn_anterior)
        self.btn_siguiente = QtGui.QPushButton(self.widget_3)
        self.btn_siguiente.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_siguiente.sizePolicy().hasHeightForWidth())
        self.btn_siguiente.setSizePolicy(sizePolicy)
        self.btn_siguiente.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Users/Lia/PycharmProjects/BookSearch/Design/ico_next_page.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_siguiente.setIcon(icon3)
        self.btn_siguiente.setObjectName(_fromUtf8("btn_siguiente"))
        self.horizontalLayout_2.addWidget(self.btn_siguiente)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.box_detalles = QtGui.QGroupBox(self.centralwidget)
        self.box_detalles.setTitle(_fromUtf8(""))
        self.box_detalles.setObjectName(_fromUtf8("box_detalles"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.box_detalles)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.titulo_value = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_value.setFont(font)
        self.titulo_value.setText(_fromUtf8(""))
        self.titulo_value.setObjectName(_fromUtf8("titulo_value"))
        self.verticalLayout_6.addWidget(self.titulo_value)
        self.autor_value = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.autor_value.setFont(font)
        self.autor_value.setStyleSheet(_fromUtf8("color: rgb(156, 156, 156)"))
        self.autor_value.setText(_fromUtf8(""))
        self.autor_value.setObjectName(_fromUtf8("autor_value"))
        self.verticalLayout_6.addWidget(self.autor_value)
        self.line = QtGui.QFrame(self.box_detalles)
        font = QtGui.QFont()
        font.setKerning(True)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.isbn_key = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.isbn_key.setFont(font)
        self.isbn_key.setObjectName(_fromUtf8("isbn_key"))
        self.verticalLayout_2.addWidget(self.isbn_key)
        self.editorial_key = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.editorial_key.setFont(font)
        self.editorial_key.setObjectName(_fromUtf8("editorial_key"))
        self.verticalLayout_2.addWidget(self.editorial_key)
        self.fecha_pub_key = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fecha_pub_key.setFont(font)
        self.fecha_pub_key.setObjectName(_fromUtf8("fecha_pub_key"))
        self.verticalLayout_2.addWidget(self.fecha_pub_key)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.isbn_value = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.isbn_value.setFont(font)
        self.isbn_value.setStyleSheet(_fromUtf8("color: rgb(157, 157, 157)"))
        self.isbn_value.setObjectName(_fromUtf8("isbn_value"))
        self.verticalLayout_4.addWidget(self.isbn_value)
        self.editorial_value = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.editorial_value.setFont(font)
        self.editorial_value.setStyleSheet(_fromUtf8("color: rgb(167, 167, 167)"))
        self.editorial_value.setObjectName(_fromUtf8("editorial_value"))
        self.verticalLayout_4.addWidget(self.editorial_value)
        self.fecha_pub_value = QtGui.QLabel(self.box_detalles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fecha_pub_value.setFont(font)
        self.fecha_pub_value.setStyleSheet(_fromUtf8("color: rgb(167, 167, 167)"))
        self.fecha_pub_value.setObjectName(_fromUtf8("fecha_pub_value"))
        self.verticalLayout_4.addWidget(self.fecha_pub_value)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.box_overview = QtGui.QWidget(self.box_detalles)
        self.box_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.box_overview.setObjectName(_fromUtf8("box_overview"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.box_overview)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_img = QtGui.QLabel(self.box_overview)
        self.label_img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img.setText(_fromUtf8(""))
        self.label_img.setObjectName(_fromUtf8("label_img"))
        self.horizontalLayout_3.addWidget(self.label_img)
        self.verticalLayout_7.addWidget(self.box_overview)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.box_detalles)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BookSearch", None))
        self.label.setText(_translate("MainWindow", "Mostrando Página No:", None))
        self.pagina_value.setText(_translate("MainWindow", "1", None))
        self.isbn_key.setText(_translate("MainWindow", "ISBN", None))
        self.editorial_key.setText(_translate("MainWindow", "Editorial", None))
        self.fecha_pub_key.setText(_translate("MainWindow", "Año de Publicación", None))
        self.isbn_value.setText(_translate("MainWindow", "ISBN no definido", None))
        self.editorial_value.setText(_translate("MainWindow", "Editorial no definida", None))
        self.fecha_pub_value.setText(_translate("MainWindow", "Año de Publicación no definido", None))

from resources import *

